import Head from "next/head";
import Image from "next/image";
import About from "./pageSection/About";
import Main from "./pageSection/Main";
import MyWork from "./pageSection/MyWork";
import Navbar from "./pageSection/Navbar";
import Services from "./pageSection/Services";
import Contact from "./pageSection/Contact";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Front-End developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Services />
      <MyWork />

      <Contact />
    </div>
  );
}
